#!/usr/bin/env node
/**
 * Copies the design system out of `design/` and into the web app, so the real screens are built from the same
 * stylesheet the mockups are, rather than a hand-rewritten imitation of it that drifts on the first tweak.
 *
 * `design/` is a standalone static board opened straight from disk (the mocks work over `file://`), so Next.js
 * never serves it. Same reason `copy-art.mjs` and `copy-box2d.mjs` exist. Both destinations are generated, not
 * authored, and are git-ignored; this runs from `apps/web`'s `predev`/`prebuild` so a fresh clone cannot miss it.
 *
 * One transformation is applied: `tokens.css` loads its fonts with paths relative to itself (`fonts/...`,
 * which is how the mocks resolve them), but in the app the stylesheet is bundled from `src/` while the fonts
 * are served from `public/`. The `@font-face` URLs are rewritten to absolute `/fonts/...` to match.
 */
import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const FONTS = [
  'jersey-15-latin-400-normal.woff2',
  'silkscreen-latin-400-normal.woff2',
  'silkscreen-latin-700-normal.woff2',
  'chakra-petch-latin-400-normal.woff2',
  'chakra-petch-latin-500-normal.woff2',
  'chakra-petch-latin-600-normal.woff2',
  'chakra-petch-latin-700-normal.woff2',
];

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const designDir = join(repoRoot, 'design');
const styleDestination = join(repoRoot, 'apps', 'web', 'src', 'design');
const fontDestination = join(repoRoot, 'apps', 'web', 'public', 'fonts');

await mkdir(styleDestination, { recursive: true });
await mkdir(fontDestination, { recursive: true });

const header = '/* GENERATED by scripts/copy-design.mjs from design/. Edit the original, not this copy. */\n';

const tokens = await readFile(join(designDir, 'tokens.css'), 'utf8');
await writeFile(
  join(styleDestination, 'tokens.css'),
  header + tokens.replaceAll("url('fonts/", "url('/fonts/"),
);

const ui = await readFile(join(designDir, 'ui.css'), 'utf8');
await writeFile(join(styleDestination, 'ui.css'), header + ui);

for (const font of FONTS) {
  await copyFile(join(designDir, 'fonts', font), join(fontDestination, font));
}

console.log(`copy-design: copied 2 stylesheets and ${FONTS.length} fonts into apps/web/`);
