#!/usr/bin/env node
/**
 * Copies the provisional game art from `design/art/` into `apps/web/public/art/`, where the browser can
 * actually load it. `design/` is a separate static board, not served by Next.js, so the game cannot read
 * from it directly — same reason `scripts/copy-box2d.mjs` exists.
 *
 * Only what the game itself renders is copied: the mockup-only assets (avatars, logos, map thumbnails,
 * whole pre-rendered scene compositions) stay in `design/` until a screen actually needs them.
 *
 * The art is generated by `node tools/art/generate.mjs` and committed, so this only ever copies; it never
 * regenerates. Runs from `apps/web`'s `predev`/`prebuild`, so a fresh clone cannot miss it. The destination
 * is generated, not authored — it is git-ignored.
 */
import { copyFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const FILES = [
  'bike/ride.png',
  'bike/lean-back.png',
  'bike/lean-forward.png',
  'bike/ragdoll-0.png',
  'bike/ragdoll-1.png',
  'bike/ragdoll-2.png',
  'bike/ragdoll-3.png',
];

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = join(repoRoot, 'design', 'art');
const destination = join(repoRoot, 'apps', 'web', 'public', 'art');

for (const file of FILES) {
  const target = join(destination, file);
  await mkdir(dirname(target), { recursive: true });
  await copyFile(join(source, file), target);
}
console.log(`copy-art: copied ${FILES.length} files to apps/web/public/art/`);
