#!/usr/bin/env node
/**
 * Copies the provisional game art from `design/art/` into `apps/web/public/art/`, where the browser can
 * actually load it. `design/` is a separate static board, not served by Next.js, so the game cannot read
 * from it directly — same reason `scripts/copy-box2d.mjs` exists.
 *
 * Only what a real screen renders is copied. That now includes the Home screen's logo, avatars, map
 * thumbnails and hero scene; the remaining pre-rendered mock compositions stay in `design/` until a screen
 * actually needs them.
 *
 * The art is generated by `node tools/art/generate.mjs` and committed, so this only ever copies; it never
 * regenerates. Runs from `apps/web`'s `predev`/`prebuild`, so a fresh clone cannot miss it. The destination
 * is generated, not authored — it is git-ignored.
 */
import { copyFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const FILES = [
  'bike/ride.png',
  'bike/lean-back.png',
  'bike/lean-forward.png',
  'bike/ragdoll-0.png',
  'bike/ragdoll-1.png',
  'bike/ragdoll-2.png',
  'bike/ragdoll-3.png',
  // Wheel-spin frames for each pose, and the impact effects. The effects were generated from the start but
  // never copied, so nothing could ever render them.
  ...['ride', 'lean-back', 'lean-forward'].flatMap((pose) =>
    [0, 1, 2, 3].map((frame) => `bike/${pose}-${frame}.png`),
  ),
  ...Array.from({ length: 6 }, (_, index) => `fx/explosion-${index}.png`),
  ...Array.from({ length: 4 }, (_, index) => `fx/dust-${index}.png`),
  // The checkpoint marshal: she replaces the plain line that used to mark a checkpoint.
  // Control-pad icons.
  'controls/gas.png',
  'controls/brake.png',
  'controls/lean-back.png',
  'controls/lean-forward.png',
  // The HD checkpoint animation: idle (8) -> activate (14, once) -> loop (24). 160x264 RGBA each.
  ...Array.from({ length: 8 }, (_, index) => `marshal-hd/idle-${index}.png`),
  ...Array.from({ length: 14 }, (_, index) => `marshal-hd/activate-${index}.png`),
  ...Array.from({ length: 24 }, (_, index) => `marshal-hd/loop-${index}.png`),
  // The Home screen's week grid, header and hero.
  'logo/rush7.png',
  ...[
    'sunset-canyon',
    'coral-coast',
    'emerald-woods',
    'steel-yard',
    'magma-ridge',
    'frost-peak',
    'orbit-circuit',
  ].map((slug) => `scenes/hero-${slug}.png`),
  'thumbs/map-1-sunset-canyon.png',
  'thumbs/map-2-coral-coast.png',
  'thumbs/map-3-emerald-woods.png',
  'thumbs/map-4-steel-yard.png',
  'thumbs/map-5-magma-ridge.png',
  'thumbs/map-6-frost-peak.png',
  'thumbs/map-7-orbit-circuit.png',
  ...Array.from({ length: 8 }, (_, index) => `avatars/a${index}.png`),
];

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = join(repoRoot, 'design', 'art');
const destination = join(repoRoot, 'apps', 'web', 'public', 'art');

for (const file of FILES) {
  const target = join(destination, file);
  await mkdir(dirname(target), { recursive: true });
  await copyFile(join(source, file), target);
}
console.log(`copy-art: copied ${FILES.length} files to apps/web/public/art/`);
